### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by justwheel** [kushaldas/lym#17]
I was looking into the repository and noticed that there was no license file in the root directory. I did see in the README that it's copyrighted to @kushaldas, but I'm not sure if this was a temporary or permanent plan (since it seems like there's also other people who have contributed to this repo already).

Since most of it is Markdown content, I would suggest adding a [Creative Commons license](https://creativecommons.org/licenses/) so the content here can remain free and open, and others can contribute knowing that their additions to the book will be added to a larger project dedicated to open knowledge.

This would also likely invite other people to contribute to the efforts of helping write the book as well. :) Plus, when you use a CC license and add it into the `LICENSE` file in the root directory, GitHub will also show the license type in the header bar and provide a brief explanation of what the license means.

**Comment by jasonbraganza** [comment]
Justin,

He plans to take all the credit :P

Seriously though, the license is a stop gap thing

He warned us the book was still too raw and we went ahead and contributed
anyway since its evolution is helping us in class

Warmest,
Jason

**Comment by justwheel** [comment]
It would still be nice to license it under a Creative Commons license now, if that is the future intent. :) This is more motivating for a potential contributor to know if my contributions would be licensed under a free and open license.

Additionally, it also makes it easy for others to cross-promote the book too. For example, if I wrote an article for Opensource.com based on one of the book's sections, I would link back and cite to the book per the requirements of the CC license, and also invite others to contribute to the book as well. Under normal copyright restrictions, I'd be more inclined to write something of my own.

**Comment by jasonbraganza** [comment]
Makes sense. Kushal, what say‽

**Comment by ghost** [comment]
Free Software licenses are good for your health :-P

**Comment by kushaldas** [comment]
I am keeping the current license as it is.

**Comment by etanot** [comment]
Hi! @kushaldas, could you please reconsider adding a license?
